name: Latest blog post workflow manual
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: 'https://dev.to/feed/zenidog8, https://medium.com/feed/@zenidog8'
